project-id: some-project-id
name: cluster name
location: europe-north1
kubeconfig: /home/user/.kube/config

images-from:
  apps/v1:
    - resource: replicasets
      jsonpath: $.spec.template.spec.containers[*].image
    - resource: statefulsets
      jsonpath: $.spec.template.spec.containers[*].image
  batch/v1:
    - resource: jobs
      jsonpath: $.spec.jobTemplate.spec.template.spec.containers[*].image
