
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-user
  labels:
    app: {{ .Release.Name }}
{{- if or (eq .Values.fasit.env.kind "legacy") (eq .Values.fasit.env.kind "tenant") }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Release.Name }}-user@{{ .Values.projectID }}.iam.gserviceaccount.com
{{- end }}
