environmentKinds:
  - legacy
  - onprem
  - tenant

values:
  projectID:
    displayName: Project ID
    description: The Google project ID
    computed:
      template: "{{ .Env.project_id | quote }}"
  managementProjectID:
    displayName: Management project ID
    description: The Google project ID where GAR resides
    computed:
      template: "{{ .Management.project_id | quote }}"
  cluster:
    displayName: Cluster name
    description: Cluster name
    computed:
      template: |
        {{ .Env.name | quote }}
  location:
    displayName: Location
    description: Location
    config:
      type: string
  log.level:
    displayName: Log level
    description: Log level
    config:
      type: string
