name: Build and deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.env"
env:
  NAME: gargle
  FEATURE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais/feature

jobs:
  build_and_push:
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    permissions:
      contents: "read"
      id-token: "write"
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4.0.1
      - name: Find go cache dir
        id: go-cache
        run: |
          go version
          # Clear cache dirs to avoid error when restoring
          go clean -cache -modcache
          echo "gocache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - name: Cache go modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # ratchet:actions/cache@v5.0.5
        with:
          path: |
            ${{ steps.go-cache.outputs.gocache }}
            ${{ steps.go-cache.outputs.gomodcache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - run: mise run test
      - run: mise run helm-lint
      - run: mise run check

      - name: Check code format and run code generators
        run: |
          mise run fmt
          git diff --exit-code --name-only

      - id: go_version
        run: echo "go_version=$(mise current go)" >> $GITHUB_OUTPUT

      - uses: nais/platform-build-push-sign@df590279b21bc5978519685752f9eaddd546043c # ratchet:nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: ${{ env.NAME }}
          build_args: |
            GO_VERSION=${{ steps.go_version.outputs.go_version }}
          google_service_account: gh-${{ env.NAME }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@dffe9a5223d84653c13374032382f6bb5de8e5ef # ratchet:fjogeleit/yaml-update-action@main
        with:
          valueFile: "charts/values.yaml"
          propertyPath: "image.tag"
          value: ${{ steps.build-push-sign.outputs.version }}
          commitChange: false

      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # ratchet:azure/setup-helm@v5.0.0
        name: "Setup Helm"
        with:
          version: "v3.14.2"

      - name: Build Chart
        run: |-
          sed -i "s/^version: .*/version: ${{ steps.build-push-sign.outputs.version }}/g" charts/Chart.yaml
          helm package charts

      - name: Push Chart
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.FEATURE_REPOSITORY }}

  deploy:
    name: Deploy
    needs:
      - build_and_push
    runs-on: fasit-deploy
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@9f870e05e92cde6cfd827b13384ec09e80be65fd # ratchet:nais/fasit-deploy@v4.1.0
        with:
          chart: ${{ env.FEATURE_REPOSITORY }}/${{ env.NAME }}
          version: ${{ needs.build_and_push.outputs.version }}
          targets: |
            [
              { "target": { "kind": "tenant", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "onprem", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "tenant" } },
              { "target": { "kind": "onprem" } }
            ]
